### ISSUE TITLE
Meta Issue to track plugins

### ISSUE THREAD

**Issue by bhaskarvk** [bhaskarvk/leaflet.extras#6]
## DONE
- [x] [Pulse Icon](https://github.com/mapshakers/leaflet-icon-pulse) Demo at [Rpubs: Pulse Icons](http://rpubs.com/bhaskarvk/leaflet-pulseIcon)
- [x] [Weather Markers](https://github.com/tallsam/Leaflet.weather-markers) Demo at [Rpubs: Weather Icons](http://rpubs.com/bhaskarvk/leaflet-weather)
- [x] [Geojson Choropleth](https://github.com/timwis/leaflet-choropleth) Demo at [Rpubs: GeoJSON Choropleth](http://rpubs.com/bhaskarvk/geojson-choropleth)
- [x] [webgl-heatmap](https://github.com/ursudio/webgl-heatmap-leaflet) Demo at [Rpubs: Heatmap](http://rpubs.com/bhaskarvk/leaflet-heatmap)
- [x] [Tile Caching](https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached) Demo at [Rpubs: Tile Caching](http://rpubs.com/bhaskarvk/TileLayer-Caching)
- [x] [Leaflet Hash](https://github.com/mlevans/leaflet-hash)
- [x] [Fullscreen Control](https://github.com/Leaflet/Leaflet.fullscreen)
- [x] [WMS Legend](https://github.com/kartoza/leaflet-wms-legend)
- [x] [Draw](https://github.com/Leaflet/Leaflet.draw)

## TO DO
- [ ] [Full Canvas](https://github.com/cyrilcherian/Leaflet-Fullcanvas)
- [ ] [GeoSearch](https://github.com/smeijer/L.GeoSearch)
- [ ] [Zoom Slider](https://github.com/kartena/Leaflet.zoomslider)
- [ ] [MaskCanvas](https://github.com/domoritz/leaflet-maskcanvas)
- [ ] [Spin](https://github.com/makinacorpus/Leaflet.Spin) May be useful with markerCluster chuncked Loading.
- [ ] [FuseSearch](https://github.com/naomap/leaflet-fusesearch) Could be really handy
- [ ] [TextPath](https://github.com/makinacorpus/Leaflet.TextPath)
- [ ] [Geometry](https://makinacorpus.github.io/Leaflet.GeometryUtil)
- [ ] [Vector Markers](https://github.com/hiasinho/Leaflet.vector-markers)
- [ ] [Condensed Attribution](https://github.com/route360/Leaflet.CondensedAttribution)
- [ ] [Responsive Attribution](https://github.com/areichman/leaflet-responsive-attribution)

**Comment by tim-salabim** [comment]
Re: canvas plugins
Have a look at 
https://github.com/environmentalinformatics-marburg/mapview/blob/develop/inst/htmlwidgets/lib/large/addLargePolygonsLines.js
and
https://github.com/environmentalinformatics-marburg/mapview/blob/develop/inst/htmlwidgets/lib/veryLarge/addVeryLargePoints.js

Both are using canvas rendering. Difference is (as far as I understand) the former uses standard html5 canvas, the latter uses open-gl canvas (adapted from Leaflet.Glify) and is currently only available for points. There are also some dirty (or elegant - depending on the point of view) hacks regarding passing of data "around and into" the widget.

Just so you are aware of what we are up to in this regard.

**Comment by bhaskarvk** [comment]
Tracking plugins like this is not very practical. Better to track individual plugins in individual issues.
